name: Docker Image CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cp .env.example .env
      - run: sed -i 's/remove-if-redis-has-no-password/test/g' .env
      - run: docker-compose up test
