name: Reindex

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make a reindex API request
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo $env:API_TOKEN
          curl -X POST -H "X-API-KEY: $env:API_TOKEN" -H "Content-Length: 0" https://search-service.redislabs.com/indexer'
